### PR TITLE
Universal SW app

### PR DESCRIPTION
**Pull request by drphilmarshall**
This PR is where I am addressing our main reconfigurability issue, https://github.com/zooniverse/Lens-Zoo/issues/276. I think I want to follow the start that @chrissnyder made in the `results` page, and make project-specific files to contain the content we use/used in each project. I'm doing this in a pull request so that we can see the changes accumulate - comments welcome any time! I'll start with the easy pages (about, home etc) and set the default app to be CFHTLS stage 1, as needed for the imminent reboot.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Hah! Check out [all that history above](https://github.com/drphilmarshall/Lens-Zoo/pull/77) - those were all the commits we made since departing from the master branch (which I am now proposing we move back to, when this consolidation work is done. Pretty cool to see everything all together like that :-) Might be useful for reference as well.

**Comment by drphilmarshall** [comment]
PS. @chrissnyder note that I am only making a pull request to our own fork's master branch. That preserves the extra layer of protection you have between my hacking and the live app :-)

**Comment by drphilmarshall** [comment]
Hey @chrissnyder would you mind helping us fix up the SW landing page please? I am trying to recover the effect we had at CFHTLS stage 2 (minus the orange color), in [`app/views/home/landingCFHTLSreboot.eco`](https://github.com/drphilmarshall/Lens-Zoo/blob/universal/app/views/home/landingCFHTLSreboot.eco). If you can help us make that look good, with your magic css wand, we can then adjust the content. Thanks! 

BTW, here is what it currently looks like for me. Square! 

image

**Comment by drphilmarshall** [comment]
Hi @chrissnyder ,

We are almost done with the content for the Space Warps site, ready for getting it back up again in the next few days (when we expect our two papers to be accepted, and our publicity splash to happen). @anupreeta27 is going to give you a list of Zoo IDs for the subjects we'd like reactivated, and I'm hoping we can finish this branch and merge it back into master before you pull it in to the live site. We need help with two things though: the FAQ has stopped loading (#78), and the formatting of the landing page has broken (#79). Do you have some time to work on this please? I don't think it will tax you very hard :-) Thanks very much!

**Comment by chrissnyder** [comment]
Looking at this today, will let you know how it goes.

**Comment by drphilmarshall** [comment]
How's it going, @chrissnyder ? :-)

**Comment by chrissnyder** [comment]
Sorry for the super long delay on this.

I think this is a great start to simplifying how we manage the repo. Couple of specific points:

- Mind if I push to this branch to fix some of the styling issues, like on the home page?
- In my perfect ideal world we have a single flag that we can change in a central place on the site to change what survey it's currently configured for. This requires that all the different spotter's guides and homepages have a consistent naming scheme, so the config value can modify all of them at once. I might be overthinking it, considering it's not that many pages.
- Changing what view we display works great. Not sure how we'd approach it yet if we needed specific JS, but maybe that's a problem for another day.

**Comment by chrissnyder** [comment]
Also, I'm 100% OK with changes like this being PRed directly to https://github.com/zooniverse/Lens-Zoo. The less we diverge, the better.

**Comment by drphilmarshall** [comment]
>
>    - Mind if I push to this branch to fix some of the styling issues,
>    like on the home page?
>
>
Please do! As soon as you are done I'll merge into master, and then submit
a PR to the zooniverse/Lens-Zoo master branch.


>
>    - In my perfect ideal world we have a single flag that we can change
>    in a central place on the site to change what survey it's currently
>    configured for. This requires that all the different spotter's guides and
>    homepages have a consistent naming scheme, so the config value can modify
>    all of them at once. I might be overthinking it, considering it's not that
>    many pages.
>
>
No, that could be nice - but let's postpone that to a separate refactoring.
Right now we need to get the site back up as quickly as possible.


>    - Changing what view we display works great. Not sure how we'd
>    approach it yet if we needed specific JS, but maybe that's a problem for
>    another day.
>
> Glad to hear it! Thanks, Chris.

**Comment by marten** [comment]
@chrissnyder While I'm loathe to say "LGTM" (because there's way too much stuff happening in places where it shouldn't; which is not something to tackle at this point), the biggest objection I'd have with this is what you already pointed out: all the blocks with "reconfiguration" comments should really be centralized to a `Configuration` module so that all the controllers etc can just reference that, eg instead of:

```
# RECONFIGURATION:
# Which survey are we providing a tutorial on? We'll need to
# specify the images to use, and the text to display, at each step.
#
TutorialSubject = require 'lib/tutorial/tutorial_subjectCFHTLS'
# TutorialSubject = require 'lib/tutorial/tutorial_subjectVICS82'
```

have something like:

```
# configuration.coffee
CFHTLSTutorialSubject = require 'lib/tutorial/tutorial_subjectCFHTLS'
VICS82TutorialSubject = require 'lib/tutorial/tutorial_subjectVICS82'

module.exports
  tutorialSubject: CFHTLSTutorialSubject
  tutorialSteps: CFHTLSRebootTutorialSteps 
  # etc

# classifier.coffee
Configuration = require 'lib/configuration'
TutorialSubject = Configuration.tutorialSubject
```

**Comment by drphilmarshall** [comment]
Agreed on all points, @marten. This branch only needs a tiny bit of css tweaking on the landing page and then it'll be ready to put up, reactivating the subjects in the list that @anupreeta27 sent. As soon as the landing page looks right, we can merge this PR into drphilmarshall/Lens-Zoo:master, and then from there merge it straight away into zooniverse/Lens-Zoo:master as@chrissnyder says. I'd then suggest we work on centralizing the reconfigurability in a new branch, zooniverse/Lens-Zoo:reconfigurability, while we go ahead and test  the site (and maybe even launch it, if we hear back from our referee this week). Sound good? Finishing off the landing page should *really not be very much work*!

**Comment by drphilmarshall** [comment]
PS. Hey @aprajita @anupreeta27 check out the conversation above. In just two years we have become more agile than the zooniverse dev team! ;-)

**Comment by aprajita** [comment]
not sure i understand what that means! but thanks to all involved in
getting this up and running!!

**Comment by chrissnyder** [comment]
@marten Many thanks for the eyes. Will be refactoring to that in just a moment.

**Comment by chrissnyder** [comment]
@drphilmarshall I don't have write access to this repo, so I merged in these changes separately at https://github.com/zooniverse/Lens-Zoo/pull/278. This PR can be closed. I do suggest that any other PRs come into zooniverse/Lens-Zoo so we have a clean history. Happy to give the whole team write access as well, so you can branch whenever.

@marten Had a start at organizing configuration at https://github.com/zooniverse/Lens-Zoo/commit/c1d579e106616ab35a56f2f57efbf77ba8282cd8. The commit is real messy because apparently my Atom setup auto-removes trailing whitespace.

There's a million more things I want to change in the repo, but those will have to come in due time.

**Comment by marten** [comment]
Just in case you didn't know this trick: adding ?w=1 to a github URL lets
it ignore diff lines that change only whitespace:
https://github.com/zooniverse/Lens-Zoo/commit/c1d579e106616ab35a56f2f57efbf77ba8282cd8?w=1

**Comment by chrissnyder** [comment]
... woah

**Comment by drphilmarshall** [comment]
Great stuff, thanks very much @chrissnyder ! I pulled all your commits in, and will now merge into our master branch which should match your one. Phew! :-)

**Pull request merged**
